apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: myapps-cname
  annotations:
    crossplane.io/external-name: myapps-cname
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/noseka1/dns-based-failover-poc//crossplane-terraform/dns/terraform?ref=master
