apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns-custom

resources:
- dnsendpoints.externaldns.k8s.io-crd.yaml
- external-dns-custom-ns.yaml
- external-dns-sa.yaml
- external-dns-credentials-secret.yaml
- external-dns-deploy.yaml
- external-dns-custom-clusterrole.yaml
- external-dns-custom-clusterrolebinding.yaml
