apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: test-1
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/noseka1/dns-based-failover-poc//crossplane-terraform/environment/terraform?ref=master
