apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: test-vpc-1
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 192.168.100.0/24
    enableDnsSupport: true
    enableDnsHostNames: true
    tags:
    - key: Name
      value: test-vpc-1
  providerConfigRef:
    name: default
