apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: test-subnet-1
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    cidrBlock: 192.168.100.0/24
    vpcIdRef:
      name: test-vpc-1
    tags:
    - key: Name
      value: test-subnet-1
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: default
